[project]
name = "travel-assistant-rag"
version = "0.1.0"
description = "Travel Assistant RAG Application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "pytest>=9.0.1",
]
